apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.appname }}
  namespace: {{ .Values.argocd.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
  project: {{ .Values.project }}
  destination:
    server: {{ .Values.cluster.address }}
    namespace: {{ .Values.cluster.namespace }}
  sources:
  {{- if .Values.dataprovider_iaa.enabled }}
  - repoURL: "https://code.europa.eu/api/v4/projects/{{ .Values.dataprovider_iaa.projectID }}/packages/helm/stable"
    targetRevision: {{ .Values.dataprovider_iaa.targetRevision }}
    chart: {{ .Values.dataprovider_iaa.chart_name }}
    helm:
      values: |
        values:
          branch: {{ .Values.dataprovider_iaa.valuesBranch }}
        project: {{ .Values.project }}
        namespaceTag: 
          authority: {{ .Values.namespaceTag.authority }}
          dataprovider: {{ .Values.namespaceTag.dataprovider }}
          common: {{ .Values.namespaceTag.common }}
        domainSuffix: {{ .Values.domainSuffix }}
        authorityDomainSuffix: {{ .Values.authorityDomainSuffix }}
        argocd:
          appname: {{ .Values.namespaceTag.dataprovider }}-dataprovider-iaa
          namespace: {{ .Values.argocd.namespace }}
        cluster:
          address: {{ .Values.cluster.address }}
          namespace: {{ .Values.cluster.namespace }}
          commonToolsNamespace: {{ .Values.cluster.commonToolsNamespace }}
          issuer: {{ .Values.cluster.issuer }}
        secrets:
          role: {{ .Values.secrets.role }}
          secretEngine: {{ .Values.secrets.secretEngine }}
        resourcePreset: {{ .Values.resourcePreset }}
        {{- if .Values.dataprovider_iaa.extraValues }}
          {{- toYaml .Values.dataprovider_iaa.extraValues  | nindent 8 }}
        {{- end }}        
  {{- end }}
  {{- if .Values.dataprovider_gaia_x_edc.enabled }}
  - repoURL: "https://code.europa.eu/api/v4/projects/{{ .Values.dataprovider_gaia_x_edc.projectID }}/packages/helm/stable"
    targetRevision: {{ .Values.dataprovider_gaia_x_edc.targetRevision }}
    chart: {{ .Values.dataprovider_gaia_x_edc.chart_name }}
    helm:
      values: |
        values:
          branch: {{ .Values.dataprovider_gaia_x_edc.valuesBranch }}
        project: {{ .Values.project }}
        namespaceTag: 
          authority: {{ .Values.namespaceTag.authority }}
          dataprovider: {{ .Values.namespaceTag.dataprovider }}
          common: {{ .Values.namespaceTag.common }}
        domainSuffix: {{ .Values.domainSuffix }}
        authorityDomainSuffix: {{ .Values.authorityDomainSuffix }}
        argocd:
          appname: {{ .Values.namespaceTag.dataprovider }}-dataprovider-gaia-x-edc
          namespace: {{ .Values.argocd.namespace }}
        cluster:
          address: {{ .Values.cluster.address }}
          namespace: {{ .Values.cluster.namespace }}
          commonToolsNamespace: {{ .Values.cluster.commonToolsNamespace }}
          issuer: {{ .Values.cluster.issuer }}
        secrets:
          role: {{ .Values.secrets.role }}
          secretEngine: {{ .Values.secrets.secretEngine }}
        resourcePreset: {{ .Values.resourcePreset }}
        {{- if .Values.dataprovider_gaia_x_edc.extraValues }}
          {{- toYaml .Values.dataprovider_gaia_x_edc.extraValues  | nindent 8 }}
        {{- end }}
  {{- end }}
  {{- if .Values.dataprovider_data1.enabled }}
  - repoURL: "https://code.europa.eu/api/v4/projects/{{ .Values.dataprovider_data1.projectID }}/packages/helm/stable"
    targetRevision: {{ .Values.dataprovider_data1.targetRevision }}
    chart: {{ .Values.dataprovider_data1.chart_name }}
    helm:
      values: |
        values:
          branch: {{ .Values.dataprovider_data1.valuesBranch }}
        project: {{ .Values.project }}
        namespaceTag: 
          authority: {{ .Values.namespaceTag.authority }}
          dataprovider: {{ .Values.namespaceTag.dataprovider }}
          common: {{ .Values.namespaceTag.common }}
        domainSuffix: {{ .Values.domainSuffix }}
        authorityDomainSuffix: {{ .Values.authorityDomainSuffix }}
        argocd:
          appname: {{ .Values.namespaceTag.dataprovider }}-dataprovider-data1
          namespace: {{ .Values.argocd.namespace }}
        cluster:
          address: {{ .Values.cluster.address }}
          namespace: {{ .Values.cluster.namespace }}
          commonToolsNamespace: {{ .Values.cluster.commonToolsNamespace }}
          issuer: {{ .Values.cluster.issuer }}
        secrets:
          role: {{ .Values.secrets.role }}
          secretEngine: {{ .Values.secrets.secretEngine }}
        resourcePreset: {{ .Values.resourcePreset }}
        {{- if .Values.dataprovider_data1.extraValues }}
          {{- toYaml .Values.dataprovider_data1.extraValues  | nindent 8 }}
        {{- end }}
  {{- end }}
  {{- if .Values.dataprovider_contract_billing.enabled }}
  - repoURL: "https://code.europa.eu/api/v4/projects/{{ .Values.dataprovider_contract_billing.projectID }}/packages/helm/stable"
    targetRevision: {{ .Values.dataprovider_contract_billing.targetRevision }}
    chart: {{ .Values.dataprovider_contract_billing.chart_name }}
    helm:
      values: |
        values:
          branch: {{ .Values.dataprovider_contract_billing.valuesBranch }}
        project: {{ .Values.project }}
        namespaceTag: 
          authority: {{ .Values.namespaceTag.authority }}
          dataprovider: {{ .Values.namespaceTag.dataprovider }}
          common: {{ .Values.namespaceTag.common }}
        domainSuffix: {{ .Values.domainSuffix }}
        argocd:
          appname: {{ .Values.namespaceTag.dataprovider }}-dataprovider-contract-billing
          namespace: {{ .Values.argocd.namespace }}
        cluster:
          address: {{ .Values.cluster.address }}
          namespace: {{ .Values.cluster.namespace }}
          commonToolsNamespace: {{ .Values.cluster.commonToolsNamespace }}
          issuer: {{ .Values.cluster.issuer }}
        secrets:
          role: {{ .Values.secrets.role }}
          secretEngine: {{ .Values.secrets.secretEngine }}
        resourcePreset: {{ .Values.resourcePreset }}
        {{- if .Values.dataprovider_contract_billing.extraValues }}
          {{- toYaml .Values.dataprovider_contract_billing.extraValues  | nindent 8 }}
        {{- end }}
  {{- end }}
  {{- if .Values.dataprovider_infrastructure.enabled }}
  - repoURL: "https://code.europa.eu/api/v4/projects/{{ .Values.dataprovider_infrastructure.projectID }}/packages/helm/stable"
    targetRevision: {{ .Values.dataprovider_infrastructure.targetRevision }}
    chart: {{ .Values.dataprovider_infrastructure.chart_name }}
    helm:
      values: |
        values:
          branch: {{ .Values.dataprovider_infrastructure.valuesBranch }}
        project: {{ .Values.project }}
        namespaceTag: 
          authority: {{ .Values.namespaceTag.authority }}
          dataprovider: {{ .Values.namespaceTag.dataprovider }}
          common: {{ .Values.namespaceTag.common }}
        domainSuffix: {{ .Values.domainSuffix }}
        argocd:
          appname: {{ .Values.namespaceTag.dataprovider }}-dataprovider-infrastructure
          namespace: {{ .Values.argocd.namespace }}
        cluster:
          address: {{ .Values.cluster.address }}
          namespace: {{ .Values.cluster.namespace }}
          commonToolsNamespace: {{ .Values.cluster.commonToolsNamespace }}
          issuer: {{ .Values.cluster.issuer }}
        secrets:
          role: {{ .Values.secrets.role }}
          secretEngine: {{ .Values.secrets.secretEngine }}
        crossplane:
          kafka:
            username: {{ .Values.namespaceTag.dataprovider }}_infrabe
            password: {{ .Values.crossplane.kafka.password }}
          gitea:
            username: gitops_test
            password: {{ .Values.crossplane.gitea.password }}
        resourcePreset: {{ .Values.resourcePreset }}
        {{- if .Values.dataprovider_infrastructure.extraValues }}
          {{- toYaml .Values.dataprovider_infrastructure.extraValues  | nindent 8 }}
        {{- end }}
  {{- end }}
  {{- if .Values.dataprovider_monitoring.enabled }}
  - repoURL: "https://code.europa.eu/api/v4/projects/{{ .Values.dataprovider_monitoring.projectID }}/packages/helm/stable"
    targetRevision: {{ .Values.dataprovider_monitoring.targetRevision }}
    chart: {{ .Values.dataprovider_monitoring.chart_name }}
    helm:
      values: |
        values:
          branch: {{ .Values.dataprovider_monitoring.valuesBranch }}
        project: {{ .Values.project }}
        namespaceTag: 
          authority: {{ .Values.namespaceTag.authority }}
          dataprovider: {{ .Values.namespaceTag.dataprovider }}
          common: {{ .Values.namespaceTag.common }}
        domainSuffix: {{ .Values.domainSuffix }}
        argocd:
          appname: {{ .Values.namespaceTag.dataprovider }}-dataprovider-monitoring
          namespace: {{ .Values.argocd.namespace }}
        cluster:
          address: {{ .Values.cluster.address }}
          namespace: {{ .Values.cluster.namespace }}
          commonToolsNamespace: {{ .Values.cluster.commonToolsNamespace }}
          issuer: {{ .Values.cluster.issuer }}
        secrets:
          role: {{ .Values.secrets.role }}
          secretEngine: {{ .Values.secrets.secretEngine }}
        resourcePreset: {{ .Values.resourcePreset }}
        {{- if .Values.dataprovider_monitoring.extraValues }}
          {{- toYaml .Values.dataprovider_monitoring.extraValues  | nindent 8 }}
        {{- end }}
  {{- end }}
  {{- if .Values.dataprovider_orchestration_platform.enabled }}
  - repoURL: "https://code.europa.eu/api/v4/projects/{{ .Values.dataprovider_orchestration_platform.projectID }}/packages/helm/stable"
    targetRevision: {{ .Values.dataprovider_orchestration_platform.targetRevision }}
    chart: {{ .Values.dataprovider_orchestration_platform.chart_name }}
    helm:
      values: |
        values:
          branch: {{ .Values.dataprovider_orchestration_platform.valuesBranch }}
        project: {{ .Values.project }}
        namespaceTag: 
          authority: {{ .Values.namespaceTag.authority }}
          dataprovider: {{ .Values.namespaceTag.dataprovider }}
          common: {{ .Values.namespaceTag.common }}
        domainSuffix: {{ .Values.domainSuffix }}
        argocd:
          appname: {{ .Values.namespaceTag.dataprovider }}-dataprovider-orchestration-platform
          namespace: {{ .Values.argocd.namespace }}
        cluster:
          address: {{ .Values.cluster.address }}
          namespace: {{ .Values.cluster.namespace }}
          commonToolsNamespace: {{ .Values.cluster.commonToolsNamespace }}
          issuer: {{ .Values.cluster.issuer }}
        secrets:
          role: {{ .Values.secrets.role }}
          secretEngine: {{ .Values.secrets.secretEngine }}
        resourcePreset: {{ .Values.resourcePreset }}
        {{- if .Values.dataprovider_orchestration_platform.extraValues }}
          {{- toYaml .Values.dataprovider_orchestration_platform.extraValues  | nindent 8 }}
        {{- end }}
  {{- end }}