contractmanager:
  extension:
    enabled: true
  url: http://contract-dataprovider:8080/contract/v1

tls:
  url:
    authenticationprovider: "http://authentication-provider:8080"

javadebug:
  enabled: false
  port: 5006

serviceAccount:
  name: simpl-edc-service-account