#Service port of component SD-Tooling-Api-Be
creationWizardApiServicePort: 8080

#Container port of component SD-Tooling-Api-Be
creationWizardApiContainerPort: 8080

#specify 'dev' for dev environment or 'dev-int' for integration environment
vaultEnvIdentifier: dev

#specify 'dev' for dev environment or 'int' for integration environment
domainUrlEnvIdentifier: dev

#Domain associated with Dev Cluster (don't modify it)
domain: dev.simpl-europe.eu

#ID of persistentVolumeClaims associated with NFS Storage
schemaVolumeClaim: nfs-storage-pvc-sd
#Mount path used for schema storage
schemaPvcMountPath: /data

#Configuration for connectivity between SD-Tooling-Api-Be and SD-Tooling-Api-Validation
validation:
  config:
    enabled: true
    #domain is the URL of SD-Tooling-Api-Validation service
    #(sd-creation-wizard-api-validation is name of Kube service associated. Check it!)
    domain: "http://sd-creation-wizard-api-validation:8080"
    # Name of Validation API Method
    validation-api: "/validate-ttl"
