# Spring Cloud Gateway Routes Participant
appConfig:
  spring:
    cloud:
      gateway:
        routes: 
          - id: keycloak
            uri: ${keycloak.url}
            predicates:
              - Path=/auth/**
            filters:
              - StripPrefix=1
          - id: users-roles
            uri: ${users-roles.url}
            predicates:
              - Path=/user-api/**
            filters:
              - StripPrefix=1
          - id: authentication-provider
            uri: ${authentication-provider.url}
            predicates:
              - Path=/auth-api/**
            filters:
              - StripPrefix=1
          # CLI configurations
          - id: cli-authentication-providerV1
            uri: ${authentication-provider.url}
            predicates:
              - Path=
                /cli/authApi/v1/csr/generate,
                /cli/authApi/v1/keypairs/generate,
                /cli/authApi/v1/keypairs,
                /cli/authApi/v1/credentials,
                /cli/authApi/v1/credentials/download,
                /cli/authApi/v1/agent/ping
            filters:
              - StripPrefix=2
              - name: ClientCredentialsFilter
                args:
                  # Here you specify the clientid and the required client role to invoke this api
                  # in the following order: 
                  # client-id-name: client-role-1, client-role-1
                  # The default configuration is shown below.
                  cli: cli-role
          - id: cli-users-and-rolesV1
            uri: ${users-roles.url}
            predicates:
              - Path=
                /cli/userApi/v1/users/import,
                /cli/userApi/v1/roles/import,
                /cli/userApi/v1/roles/*/identityAttributes
            filters:
              - StripPrefix=2
              - name: ClientCredentialsFilter
                args:
                  # Here you specify the clientid and the required client role to invoke this api
                  # in the following order: 
                  # client-id-name: client-role-1, client-role-1
                  # The default configuration is shown below.
                  cli: cli-role

  springdoc:
    swagger-ui:
      urls:
        - url: /user-api/v3/api-docs
          name: Users & Roles Service
        - url: /auth-api/v3/api-docs
          name: Authentication Provider Service

  keycloak:
    app:
      realm: participant

  routes:
    public-urls:
      - method: GET
        path: "/swagger-ui.html"
      - method: GET
        path: "/swagger-ui/**"
      - method: GET
        path: "/v3/api-docs/**"
      - method: GET
        path: "/actuator/**"

    denied-urls:
      - method: GET
        path: "/auth-api/keypair"
      - method: GET
        path: "/authApi/v1/keypairs"
      - path: "/user-api/mtls/**"
      - path: "/auth-api/mtls/**"
      - path: "/userApi/v1/mtls/**"
      - path: "/authApi/v1/mtls/**"

    rbac:
      - path: "/sdtooling-api/**"
        method: GET
        roles:
          - SD_PUBLISHER
      - path: "/sdtooling-api/**"
        method: POST
        roles:
          - SD_PUBLISHER 
      - path: "/signer/**"
        method: GET
        roles:
          - SD_PUBLISHER
      - path: "/signer/**"
        method: POST
        roles:
          - SD_PUBLISHER
      - path: "/xsfc-advsearch-be/**"
        method: GET
        roles:
          - SD_PUBLISHER
          - SD_CONSUMER
      - path: "/xsfc-advsearch-be/**"
        method: POST
        roles:
          - SD_PUBLISHER
          - SD_CONSUMER
      - path: "/contract-consumption/**"
        method: GET
        roles:
          - SD_CONSUMER
      - path: "/contract-consumption/**"
        method: POST
        roles:
          - SD_CONSUMER
      - path: "/user-api/agent/identity-attributes"
        method: GET
        roles:
          - T1UAR_M
      - path: "/user-api/agent/identity-attributes/*"
        method: GET
        roles:
          - T1UAR_M
      - path: "/user-api/identity-attribute/search"
        method: GET
        roles:
          - T1UAR_M
      - path: "/user-api/role/*"
        method: GET
        roles:
          - T1UAR_M
      - path: "/user-api/role"
        method: PUT
        roles:
          - T1UAR_M
      - path: "/user-api/role/*/identity-attributes"
        method: POST
        roles:
          - T1UAR_M
      - path: "/user-api/role/*/identity-attributes"
        method: PUT
        roles:
          - T1UAR_M
          - ONBOARDER_M          
      - path: "/user-api/role/delete-attribute"
        method: DELETE
        roles:
          - T1UAR_M
      - path: "/user-api/role/*"
        method: DELETE
        roles:
          - T1UAR_M
      - path: "/user-api/role/search"
        method: GET
        roles:
          - T1UAR_M
      - path: "/user-api/role/*/duplicate-identity-attribute"
        method: POST
        roles:
          - T1UAR_M
      - path: "/user-api/user/as-t1user"
        method: POST
        roles:
          - T1UAR_M
      - path: "/user-api/user/*"
        method: GET
        roles:
          - T1UAR_M
      - path: "/user-api/user/*"
        method: PUT
        roles:
          - T1UAR_M
      - path: "/user-api/user/*"
        method: DELETE
        roles:
          - T1UAR_M
      - method: POST
        path: "/auth-api/keypair/import"
        roles:
          - ONBOARDER_M 
      - path: "/auth-api/keypair/**"
        roles:
          - ONBOARDER_M 
      - method: POST
        path: "/auth-api/csr/generate"
        roles:
          - ONBOARDER_M 
      - path: "/auth-api/keypair"
        method: HEAD
        roles:
          - ONBOARDER_M
