project: ${PROJECT}
domainSuffix: ${DOMAINSUFFIX}
authorityDomainSuffix: ${AUTHORITYDOMAINSUFFIX}
namespaceTag:
  dataprovider: ${NAMESPACETAG}
  authority: ${AUTHNAMESPACETAG}
  common: ${COMMONSPACETAG}

resourcePreset: default
# resourcePreset: low

argocd:
  appname: ${NAMESPACE}
  namespace: argocd

cluster:
  address: https://kubernetes.default.svc
  namespace: ${NAMESPACE}
  commonToolsNamespace: ${COMMONNAMESPACE}
  issuer: ${CLUSTERISSUER}

secrets:
  secretEngine: ${SECRETENGINE}
  role: ${SECRETROLE}

crossplane:
  kafka:
    password: ${KAFKAPASS}
  gitea:
    password: ${GITEAPASS}

dataprovider_iaa:
  enabled: true
  projectID: "1403"
  targetRevision: 1.2.23
  chart_name: provider-iaa
  valuesBranch: v1.2.23

dataprovider_gaia_x_edc:
  enabled: true
  projectID: "1400"
  targetRevision: 1.0.4
  chart_name: provider-gaia-x-edc
  valuesBranch: v1.0.4

dataprovider_data1:
  enabled: true
  projectID: "1397"
  targetRevision: 1.1.6
  chart_name: provider-data1
  valuesBranch: v1.1.6

dataprovider_contract_billing:
  enabled: true
  projectID: "1405"
  targetRevision: 0.0.7
  chart_name: provider-contract-billing
  valuesBranch: v0.0.7

dataprovider_infrastructure:
  enabled: true
  projectID: "1407"
  targetRevision: 1.0.3
  chart_name: provider-infrastructure
  valuesBranch: v1.0.3

dataprovider_monitoring:
  enabled: true
  projectID: "1395"
  targetRevision: 0.0.6
  chart_name: provider-monitoring
  valuesBranch: v0.0.6

dataprovider_orchestration_platform:
  enabled: true
  projectID: "1410"
  targetRevision: 0.1.16
  chart_name: provider-orchestration-platform
  valuesBranch: v0.1.16
