primary:
  initdb:
    scripts:
      init.sql: |
        CREATE USER keycloak WITH PASSWORD 'keycloak' CREATEDB;
        CREATE DATABASE keycloak OWNER keycloak;
        CREATE USER users WITH PASSWORD 'users' CREATEDB;
        CREATE DATABASE users OWNER users;
        CREATE DATABASE "credential-db" OWNER users;
