primary:
  initdb:
    scripts:
      init.sql: |
        CREATE USER keycloak WITH PASSWORD 'keycloak' CREATEDB;
        CREATE DATABASE keycloak OWNER keycloak;
        CREATE USER usersroles WITH PASSWORD 'usersroles' CREATEDB;
        CREATE DATABASE usersroles OWNER usersroles;
        CREATE USER authenticationprovider WITH PASSWORD 'authenticationprovider' CREATEDB;
        CREATE DATABASE authenticationprovider OWNER authenticationprovider;
        CREATE USER edc WITH PASSWORD 'edc' CREATEDB;
        CREATE DATABASE edc OWNER edc;