SERVICE_PORT: 8084
CONTAINER_PORT: 8084
DEPLOYMENT_IMAGE_PULL_POLICY: Always
REPOSITORY: "code.europa.eu:4567/simpl/simpl-open/development/gaia-x-edc/poc-gaia-edc/simpl-backend"
TAG: "latest"

secretConfigPath: "{{ .Values.hashicorp.secretEngine }}/{{ .Release.Namespace }}-infra-adapter-simpl-backend"

ingress:
  host: adapter-infra.{{ .Values.namespaceTag.dataprovider }}.{{ .Values.domainSuffix }}
  tls:
    secretName: adapter-infra-simpl-backend-tls
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "false"

deployment:
  label: infra-deployment
  