ingress:
  issuer: dev-prod

microfrontends:
- name: usersroles
  application: usersandroles
  path: "/users-roles"
- name: participant
  application: participant-utility
  path: "/participant-utility"
